-- Table: Treatments
CREATE TABLE Treatments (
    TreatmentID SERIAL PRIMARY KEY,
    TreatmentName VARCHAR(100),
    Description TEXT,
    Cost NUMERIC(10, 2),
    DurationHours INT,
    DateAdministered DATE,
    FollowUpRequired BOOLEAN,
    Notes TEXT
)

INSERT INTO Treatments (TreatmentName, Description, Cost, DurationHours, DateAdministered, FollowUpRequired, Notes) VALUES
('Physical Therapy Session - Knee', 'Strengthening exercises for quadriceps and hamstrings.', 175.50, 1, '2023-05-10', TRUE, 'Patient reported mild soreness post-session.'),
('Appendectomy - Laparoscopic', 'Surgical removal of the appendix via laparoscopy.', 11500.00, 2, '2024-01-22', TRUE, 'Procedure successful, minimal blood loss.'),
('Chemotherapy - Cycle 1 (Cisplatin)', 'Intravenous administration of Cisplatin agent.', 2500.75, 4, '2023-11-01', TRUE, 'Patient tolerated well, anti-nausea meds given.'),
('X-Ray - Chest (2 Views)', 'Standard posterior-anterior and lateral chest radiography.', 120.00, 0, '2024-02-15', FALSE, 'Image quality satisfactory.'),
('Dental Cleaning - Routine', 'Prophylaxis, scaling, and polishing of teeth.', 150.00, 1, '2023-09-05', FALSE, 'Mild plaque noted. Advised flossing technique.'),
('Vaccination - Influenza', 'Administration of seasonal flu vaccine.', 35.00, 0, '2023-10-12', FALSE, 'Administered in left deltoid.'),
('Counseling Session - Anxiety Management', 'Cognitive Behavioral Therapy techniques discussed.', 150.00, 1, '2024-03-01', TRUE, 'Patient engaged, assigned homework.'),
('Wound Debridement - Small Laceration', 'Cleaning and removal of non-viable tissue from wound.', 250.00, 1, '2023-12-05', TRUE, 'Wound bed clean. Dressing applied.'),
('MRI Scan - Brain (with contrast)', 'Magnetic resonance imaging of the brain with contrast agent.', 1800.50, 1, '2024-01-10', FALSE, 'Patient claustrophobic, required coaching.'),
('Medication Administration - IV Antibiotics', 'Infusion of Vancomycin 1g.', 85.00, 1, '2023-08-15', FALSE, 'Infusion completed without reaction.'),
('Cataract Surgery - Left Eye', 'Phacoemulsification and intraocular lens implant.', 4500.00, 1, '2023-07-20', TRUE, 'Patient vision improved post-op.'),
('Physical Therapy Session - Shoulder', 'Range of motion and rotator cuff exercises.', 180.00, 1, '2023-06-12', TRUE, 'Focus on external rotation strength.'),
('Colonoscopy - Screening', 'Endoscopic examination of the colon.', 1500.00, 1, '2024-02-28', TRUE, '2 small polyps removed and sent to pathology.'),
('Ultrasound - Abdominal', 'Imaging of abdominal organs using sound waves.', 450.00, 1, '2023-11-18', FALSE, 'Gallbladder visualized, no stones.'),
('Suture Placement - 3cm Laceration', 'Closure of forehead laceration with 5-0 nylon sutures.', 300.00, 1, '2024-01-08', TRUE, 'Good edge approximation achieved.'),
('Allergy Testing - Skin Prick', 'Testing for common environmental allergens.', 350.00, 1, '2023-09-26', TRUE, 'Positive reaction to dust mites and grass pollen.'),
('Electrocardiogram (ECG/EKG)', 'Recording of the electrical activity of the heart.', 75.00, 0, '2024-03-11', FALSE, 'Normal sinus rhythm recorded.'),
('Blood Transfusion - 1 Unit Packed Red Blood Cells', 'Intravenous infusion of PRBCs for anemia.', 600.00, 3, '2023-10-04', FALSE, 'Patient vitals stable during transfusion.'),
('Psychiatric Evaluation - Initial', 'Comprehensive assessment of mental health status.', 350.00, 2, '2024-02-09', TRUE, 'Diagnosis discussed, treatment plan initiated.'),
('Joint Injection - Knee (Cortisone)', 'Intra-articular injection of corticosteroid for arthritis pain.', 220.00, 0, '2023-12-19', TRUE, 'Patient reported immediate partial relief.'),
('Biopsy Collection - Skin Lesion', 'Shave biopsy of suspicious mole on back.', 280.00, 0, '2024-01-25', TRUE, 'Specimen sent to pathology.'),
('Radiation Therapy - Session 5', 'Targeted radiation dose administered for tumor treatment.', 950.00, 1, '2023-08-29', TRUE, 'Patient reported mild fatigue.'),
('Splint Application - Wrist Sprain', 'Application of volar wrist splint for immobilization.', 125.00, 0, '2024-03-05', TRUE, 'Instructed patient on care and warning signs.'),
('Dental Filling - Composite (1 Surface)', 'Removal of decay and placement of tooth-colored filling.', 210.00, 1, '2023-11-22', FALSE, 'Occlusion checked and adjusted.'),
('Sleep Study (Polysomnography)', 'Overnight monitoring of sleep patterns and physiological data.', 2200.00, 8, '2024-02-14', TRUE, 'Study completed, data analysis pending.'),
('Nutritional Counseling - Diabetes Management', 'Dietary education focused on blood sugar control.', 130.00, 1, '2023-10-17', TRUE, 'Provided meal planning resources.'),
('Suture Removal - Forehead Laceration', 'Removal of sutures placed previously.', 75.00, 0, '2024-01-15', FALSE, 'Wound healing well, advised scar care.'),
('Nebulizer Treatment - Albuterol', 'Inhalation therapy for bronchospasm.', 50.00, 0, '2023-09-11', FALSE, 'Patient breathing improved post-treatment.'),
('Dialysis Session - Hemodialysis', 'Blood filtration procedure for kidney failure.', 750.00, 4, '2024-03-12', TRUE, 'Patient tolerated session well, fluid removal target met.'),
('Casting - Forearm Fracture', 'Application of fiberglass cast for fracture immobilization.', 380.00, 1, '2023-12-28', TRUE, 'Post-reduction X-ray confirmed good alignment.'),
('Hearing Test (Audiometry)', 'Comprehensive assessment of hearing acuity.', 160.00, 1, '2024-01-30', FALSE, 'Mild high-frequency loss noted bilaterally.'),
('Vaccination - Tdap Booster', 'Tetanus, diphtheria, and pertussis vaccine administration.', 65.00, 0, '2023-08-08', FALSE, 'Standard booster dose given.'),
('Physical Therapy Session - Back Pain', 'Core strengthening and flexibility exercises.', 170.00, 1, '2024-02-20', TRUE, 'Patient demonstrated exercises correctly.'),
('Endoscopy - Upper GI (EGD)', 'Examination of esophagus, stomach, and duodenum.', 1350.00, 1, '2023-10-24', TRUE, 'Mild gastritis noted. Biopsies taken.'),
('CT Scan - Head (without contrast)', 'Computed tomography imaging of the head.', 950.00, 0, '2024-03-07', FALSE, 'Scan completed quickly.'),
('Incision and Drainage - Abscess', 'Surgical drainage of skin abscess.', 400.00, 1, '2023-11-14', TRUE, 'Packed with iodoform gauze.'),
('Electroencephalogram (EEG)', 'Recording of brain electrical activity.', 650.00, 1, '2024-01-18', FALSE, 'Patient cooperative during recording.'),
('Root Canal Therapy - Molar', 'Treatment of infected tooth pulp.', 1200.00, 2, '2023-09-19', TRUE, 'Temporary filling placed.'),
('Cryotherapy - Skin Wart Removal', 'Application of liquid nitrogen to destroy wart tissue.', 95.00, 0, '2024-02-27', TRUE, 'Patient advised blistering is expected.'),
('Lumbar Puncture', 'Collection of cerebrospinal fluid via spinal needle.', 700.00, 1, '2023-12-12', FALSE, 'Procedure performed under sterile conditions.'),
('Burn Dressing Change - Second Degree', 'Cleaning and application of new dressing to burn wound.', 110.00, 0, '2024-01-04', TRUE, 'No signs of infection noted.'),
('Stress Test - Exercise Treadmill', 'Monitoring heart activity during controlled exercise.', 550.00, 1, '2023-11-07', FALSE, 'Test negative for ischemia.'),
('Family Therapy Session', 'Counseling session involving multiple family members.', 220.00, 1, '2024-03-14', TRUE, 'Focused on communication patterns.'),
('Removal of Impacted Cerumen', 'Manual or irrigation removal of ear wax.', 100.00, 0, '2023-08-22', FALSE, 'Tympanic membrane visualized clearly post-procedure.'),
('Pap Smear Collection', 'Collection of cervical cells for screening.', 85.00, 0, '2024-02-22', FALSE, 'Specimen sent to lab.'),
('Bone Density Scan (DEXA)', 'Measurement of bone mineral density.', 250.00, 0, '2023-10-10', FALSE, 'Scan focused on hip and spine.'),
('Angioplasty - Coronary Artery', 'Procedure to open blocked heart artery with balloon/stent.', 25000.00, 3, '2023-09-13', TRUE, 'Successful stent placement in LAD artery.'),
('Vision Exam - Routine', 'Assessment of visual acuity and eye health.', 140.00, 1, '2024-01-19', FALSE, 'Prescription updated.'),
('Occupational Therapy Session - Hand Injury', 'Exercises and modalities to improve hand function.', 190.00, 1, '2024-02-06', TRUE, 'Patient working on fine motor skills.'),
('Holter Monitor Application (24hr)', 'Placement of device to record continuous ECG.', 300.00, 0, '2023-11-28', TRUE, 'Patient instructed on diary keeping.'),
('Medication Injection - B12', 'Intramuscular injection of Vitamin B12.', 40.00, 0, '2024-03-04', FALSE, 'Standard monthly dose.'),
('Laser Eye Surgery - LASIK Consult', 'Evaluation for refractive laser eye surgery.', 150.00, 1, '2023-12-07', FALSE, 'Patient deemed a potential candidate.'),
('Skin Graft - Burn Wound', 'Surgical placement of skin graft over burn area.', 9500.00, 3, '2023-10-26', TRUE, 'Graft site healing well initially.'),
('Prenatal Ultrasound - Anatomy Scan', 'Detailed ultrasound examination around 20 weeks gestation.', 550.00, 1, '2024-01-11', FALSE, 'Fetal anatomy appears normal.'),
('Tooth Extraction - Simple', 'Removal of a single tooth without surgical intervention.', 180.00, 1, '2023-08-17', TRUE, 'Local anesthesia used.'),
('Pulmonary Function Test (PFT)', 'Measurement of lung volumes and airflow.', 320.00, 1, '2024-02-16', FALSE, 'Results indicate mild obstruction.'),
('Group Therapy Session - Depression Support', 'Therapy session with multiple participants.', 75.00, 2, '2023-11-09', TRUE, 'Peer support encouraged.'),
('Set Broken Finger', 'Reduction and splinting of finger fracture.', 290.00, 1, '2024-03-08', TRUE, 'Buddy taping applied.'),
('Chlamydia/Gonorrhea Test Collection', 'Urine sample collected for STD testing.', 60.00, 0, '2023-10-19', FALSE, 'Sample sent for nucleic acid amplification testing.'),
('Foreign Body Removal - Ear', 'Extraction of foreign object (bead) from ear canal.', 200.00, 0, '2024-01-23', FALSE, 'Object removed successfully with forceps.'),
('Cardiac Catheterization - Diagnostic', 'Invasive procedure to visualize heart arteries.', 8000.00, 2, '2023-12-14', TRUE, 'Moderate stenosis found in RCA.'),
('Speech Therapy Session - Stuttering', 'Therapy focused on fluency techniques.', 160.00, 1, '2024-02-29', TRUE, 'Practiced controlled breathing exercises.'),
('Vaccination - MMR (Measles, Mumps, Rubella)', 'Combined vaccine administration.', 95.00, 0, '2023-09-07', FALSE, 'Given subcutaneously.'),
('Thyroid Ultrasound', 'Imaging of the thyroid gland.', 380.00, 0, '2024-01-09', FALSE, 'Nodule identified, measurement taken.'),
('Amniocentesis', 'Procedure to sample amniotic fluid.', 1400.00, 1, '2023-11-16', TRUE, 'Performed under ultrasound guidance.'),
('Manual Adjustment - Chiropractic (Spinal)', 'Manual manipulation of the spine.', 85.00, 0, '2024-03-01', TRUE, 'Patient reported temporary relief.'),
('IV Hydration Therapy', 'Administration of intravenous fluids for dehydration.', 150.00, 2, '2023-12-21', FALSE, 'Patient symptoms improved post-hydration.'),
('Gallbladder Removal (Cholecystectomy) - Laparoscopic', 'Surgical removal of gallbladder.', 14000.00, 2, '2024-02-01', TRUE, 'Patient tolerated procedure well.'),
('Wart Freezing (Cryosurgery) - Repeat Tx', 'Second application of liquid nitrogen to resistant wart.', 95.00, 0, '2024-03-13', TRUE, 'Slightly larger area treated this time.'),
('Echocardiogram', 'Ultrasound imaging of the heart.', 650.00, 1, '2023-10-31', FALSE, 'Normal ejection fraction noted.'),
('Medication Management Visit - Psychiatry', 'Follow-up visit to monitor psychiatric medications.', 175.00, 1, '2024-01-16', TRUE, 'Adjusted antidepressant dosage.'),
('Tonsillectomy and Adenoidectomy', 'Surgical removal of tonsils and adenoids.', 7500.00, 2, '2023-09-28', TRUE, 'Commonly performed for sleep apnea or recurrent infections.'),
('Fluorescein Angiography - Eye', 'Imaging of retinal blood vessels using dye.', 480.00, 1, '2023-11-21', FALSE, 'No leakage detected.'),
('Trigger Point Injection - Back Muscle', 'Injection of local anesthetic into muscle knot.', 180.00, 0, '2024-02-08', TRUE, 'Patient reported immediate muscle relaxation.'),
('Fecal Occult Blood Test Kit Dispense', 'Providing kit and instructions for at-home stool testing.', 25.00, 0, '2023-08-01', FALSE, 'Patient educated on sample collection.'),
('Placement of Intrauterine Device (IUD)', 'Insertion of IUD for contraception.', 550.00, 0, '2024-01-31', TRUE, 'Placement confirmed by visualization of strings.'),
('Nerve Conduction Study (NCS)', 'Measurement of nerve electrical signal speed.', 700.00, 1, '2023-12-05', FALSE, 'Study performed on lower extremities.'),
('Dental Crown Placement - Porcelain', 'Cementation of artificial tooth crown.', 1400.00, 2, '2024-03-06', TRUE, 'Margin sealed well.'),
('Vaccination - Hepatitis B Series (Dose 1)', 'First dose of Hepatitis B vaccine.', 70.00, 0, '2023-10-03', TRUE, 'Scheduled follow-up for next dose.'),
('Hernia Repair - Inguinal (Open)', 'Surgical repair of groin hernia.', 9800.00, 2, '2023-11-30', TRUE, 'Mesh placement successful.'),
('Psychotherapy Session - Trauma Focused', 'Therapy addressing past traumatic experiences.', 180.00, 1, '2024-02-15', TRUE, 'Patient processing difficult memories.'),
('Cast Removal - Forearm', 'Removal of fiberglass cast.', 100.00, 0, '2024-02-12', TRUE, 'Skin intact, mild muscle atrophy noted.'),
('Urinalysis - Dipstick and Microscopic', 'Laboratory analysis of urine sample.', 45.00, 0, '2024-03-11', FALSE, 'Results pending.'),
('Mastectomy - Simple', 'Surgical removal of breast tissue.', 16000.00, 3, '2023-10-11', TRUE, 'Drain placed post-operatively.'),
('Venipuncture for Lab Tests', 'Blood draw from vein for laboratory analysis.', 30.00, 0, '2024-01-29', FALSE, 'Samples collected for CBC and CMP.'),
('Acupuncture Session', 'Insertion of fine needles for therapeutic purposes.', 110.00, 1, '2023-12-20', TRUE, 'Focused on lower back pain points.'),
('Antibiotic Injection - Ceftriaxone', 'Intramuscular injection of antibiotic.', 75.00, 0, '2024-02-23', FALSE, 'Administered for suspected infection.'),
('Sigmoidoscopy', 'Endoscopic examination of the lower colon.', 900.00, 1, '2023-11-02', TRUE, 'No abnormalities found in sigmoid colon.'),
('Ortho Consult - Foot Pain', 'Specialist consultation regarding foot ailment.', 250.00, 1, '2024-01-05', TRUE, 'Recommended imaging and orthotics.'),
('Hysterectomy - Vaginal', 'Surgical removal of the uterus via the vagina.', 17500.00, 3, '2023-09-06', TRUE, 'Patient recovering well post-op.'),
-- Rows 101-200
INSERT INTO Treatments (TreatmentName, Description, Cost, DurationHours, DateAdministered, FollowUpRequired, Notes) VALUES
('Physical Therapy - Gait Training', 'Instruction and practice in walking patterns.', 170.00, 1, '2023-05-17', TRUE, 'Focus on heel-toe pattern.'),
('Knee Arthroscopy - Meniscus Repair', 'Minimally invasive surgery to repair knee cartilage.', 8500.00, 2, '2024-02-05', TRUE, 'Successful repair of medial meniscus tear.'),
('Chemotherapy - Cycle 2 (Paclitaxel)', 'Intravenous administration of Paclitaxel.', 2800.00, 4, '2023-11-15', TRUE, 'Patient experienced mild neuropathy.'),
('X-Ray - Ankle (3 Views)', 'Radiography of the ankle joint.', 135.00, 0, '2024-03-01', FALSE, 'No fracture identified.'),
('Dental Sealant Application', 'Protective coating applied to molar surfaces.', 60.00, 1, '2023-09-12', FALSE, 'Applied to permanent molars.'),
('Vaccination - Pneumococcal (PCV13)', 'Administration of pneumococcal conjugate vaccine.', 180.00, 0, '2023-10-19', FALSE, 'Recommended for age group.'),
('Couples Counseling Session', 'Therapy session involving a couple.', 200.00, 1, '2024-03-08', TRUE, 'Worked on conflict resolution skills.'),
('Wound Packing Change - Abscess', 'Removal of old packing and insertion of new.', 90.00, 0, '2023-12-12', TRUE, 'Wound showing signs of healing.'),
('MRI Scan - Lumbar Spine (without contrast)', 'Magnetic resonance imaging of the lower back.', 1650.00, 1, '2024-01-17', FALSE, 'Findings discussed with referring physician.'),
('Medication Injection - Insulin Teaching', 'Instruction on self-administration of insulin.', 75.00, 1, '2023-08-23', TRUE, 'Patient demonstrated correct technique.'),
('Coronary Artery Bypass Graft (CABG) x3', 'Open-heart surgery to bypass blocked coronary arteries.', 75000.00, 6, '2023-07-27', TRUE, 'Patient transferred to ICU post-op.'),
('Physical Therapy - Ultrasound Therapy', 'Therapeutic ultrasound applied to soft tissue.', 100.00, 0, '2023-06-19', TRUE, 'Used for shoulder tendonitis.'),
('Flexible Sigmoidoscopy with Biopsy', 'Endoscopic exam with tissue sampling.', 1050.00, 1, '2024-03-15', TRUE, 'Biopsy taken from inflamed area.'),
('Ultrasound - Pelvic (Transvaginal)', 'Imaging of pelvic organs via transvaginal probe.', 480.00, 1, '2023-11-25', FALSE, 'Ovaries appear normal.'),
('Laceration Repair - Scalp (Staples)', 'Closure of scalp wound using surgical staples.', 320.00, 1, '2024-01-15', TRUE, 'Hemostasis achieved.'),
('Allergy Immunotherapy Injection', 'Subcutaneous injection for allergy desensitization.', 55.00, 0, '2023-10-02', TRUE, 'Maintenance dose administered.'),
('Spirometry Testing', 'Measurement of airflow during breathing.', 120.00, 0, '2024-03-18', FALSE, 'Performed pre and post bronchodilator.'),
('Blood Culture Collection', 'Collection of blood samples to test for infection.', 150.00, 0, '2023-10-10', FALSE, 'Two sets collected from different sites.'),
('Psychiatric Medication Management Follow-up', 'Monitoring effectiveness and side effects of psych meds.', 160.00, 1, '2024-02-13', TRUE, 'No changes needed at this time.'),
('Joint Aspiration - Knee', 'Removal of excess fluid from the knee joint.', 300.00, 0, '2024-01-02', TRUE, 'Fluid sent for analysis.'),
('Skin Biopsy - Punch Technique', 'Removal of a small core of skin for analysis.', 310.00, 0, '2024-02-02', TRUE, 'Closure with single suture.'),
('Radiation Therapy - Planning Session', 'CT simulation and treatment planning.', 1500.00, 2, '2023-08-07', TRUE, 'Target volumes defined.'),
('Application of Walking Boot', 'Fitting and application of boot for foot/ankle injury.', 180.00, 0, '2024-03-12', TRUE, 'Patient instructed on use and precautions.'),
('Dental Extraction - Surgical (Wisdom Tooth)', 'Surgical removal of impacted wisdom tooth.', 450.00, 1, '2023-11-29', TRUE, 'Post-op instructions provided.'),
('Vestibular Rehabilitation Therapy', 'Exercises to treat dizziness and balance disorders.', 190.00, 1, '2024-02-21', TRUE, 'Patient performed gaze stabilization exercises.'),
('Nutritional Assessment - Initial', 'Comprehensive evaluation of dietary intake and needs.', 200.00, 1, '2023-10-24', TRUE, 'Recommendations provided.'),
('Staple Removal - Scalp Laceration', 'Removal of surgical staples.', 80.00, 0, '2024-01-22', FALSE, 'Wound edges well approximated.'),
('Continuous Glucose Monitor (CGM) Placement', 'Insertion of sensor for continuous glucose monitoring.', 250.00, 0, '2023-09-18', TRUE, 'Patient trained on device usage.'),
('Hemodialysis Catheter Placement', 'Insertion of central venous catheter for dialysis access.', 1800.00, 1, '2024-03-19', TRUE, 'Placement confirmed by X-ray.'),
('Cast Check and Adjustment', 'Evaluation of cast fit and integrity.', 95.00, 0, '2024-01-11', TRUE, 'No issues identified.'),
('Tympanometry Test', 'Measurement of middle ear function.', 70.00, 0, '2024-02-06', FALSE, 'Type A tympanogram obtained bilaterally.'),
('Vaccination - Varicella (Chickenpox)', 'Administration of varicella vaccine.', 140.00, 0, '2023-08-15', FALSE, 'Given as part of routine childhood schedule.'),
('Physical Therapy - Modality (Heat Pack)', 'Application of moist heat pack.', 45.00, 0, '2024-02-27', TRUE, 'Applied to lower back prior to exercise.'),
('Colonoscopy with Polypectomy', 'Endoscopic exam with removal of polyps.', 1750.00, 1, '2023-11-01', TRUE, 'Two polyps removed via snare cautery.'),
('CT Scan - Abdomen/Pelvis (with contrast)', 'Imaging of abdomen and pelvis with contrast.', 1950.00, 1, '2024-03-14', FALSE, 'Patient tolerated contrast well.'),
('Drain Removal - Surgical Site', 'Removal of post-operative drain.', 110.00, 0, '2023-11-21', FALSE, 'Drain output minimal prior to removal.'),
('Electromyography (EMG)', 'Recording electrical activity of muscles.', 750.00, 1, '2024-01-25', FALSE, 'Testing performed on affected limb.'),
('Dental Bridge Preparation', 'Preparation of teeth for dental bridge placement.', 900.00, 2, '2023-09-26', TRUE, 'Impressions taken.'),
('Laser Therapy - Skin Resurfacing Consult', 'Consultation regarding laser treatment for skin.', 180.00, 1, '2024-03-02', FALSE, 'Discussed expected results and downtime.'),
('Lumbar Epidural Steroid Injection', 'Injection into epidural space for back pain relief.', 850.00, 1, '2023-12-19', TRUE, 'Performed under fluoroscopic guidance.'),
('Burn Wound Care - Silvadene Application', 'Application of silver sulfadiazine cream.', 60.00, 0, '2024-01-18', TRUE, 'Helps prevent infection.'),
('Cardiac Monitoring - Event Monitor (30 day)', 'Patient education and application of event monitor.', 450.00, 1, '2023-11-14', TRUE, 'Patient understands how to record events.'),
('Substance Abuse Counseling Session', 'Therapy focused on addiction recovery.', 140.00, 1, '2024-03-21', TRUE, 'Discussed triggers and coping mechanisms.'),
('Cerumen Removal - Irrigation', 'Flushing ear canal to remove impacted wax.', 100.00, 0, '2023-08-29', FALSE, 'Successful removal.'),
('Colposcopy with Biopsy', 'Magnified examination of cervix with tissue sampling.', 600.00, 1, '2024-02-29', TRUE, 'Biopsies taken from abnormal areas.'),
('Mammogram - Screening (3D Tomosynthesis)', 'Digital breast tomosynthesis for cancer screening.', 380.00, 0, '2023-10-17', FALSE, 'Images sent for interpretation.'),
('Hip Replacement Surgery - Total (THR)', 'Surgical replacement of the hip joint.', 35000.00, 4, '2023-09-20', TRUE, 'Patient ambulating with walker post-op day 1.'),
('Ophthalmology Exam - Dilated Fundus', 'Examination of the back of the eye after dilation.', 190.00, 1, '2024-02-01', FALSE, 'Retina and optic nerve appear healthy.'),
('Occupational Therapy - Splint Fabrication', 'Custom creation of hand/wrist splint.', 250.00, 1, '2024-02-13', TRUE, 'Splint fabricated for carpal tunnel syndrome.'),
('Holter Monitor Removal and Data Download', 'Removing monitor and downloading ECG data.', 75.00, 0, '2023-12-01', FALSE, 'Data ready for physician review.'),
('Testosterone Injection', 'Intramuscular injection of testosterone cypionate.', 60.00, 0, '2024-03-11', FALSE, 'Regular hormone replacement therapy.'),
('Phototherapy - UVB for Psoriasis', 'Ultraviolet light treatment session.', 120.00, 0, '2023-12-14', TRUE, 'Patient tolerated session well.'),
('Skin Graft Follow-up Care', 'Assessment and dressing change for skin graft.', 150.00, 0, '2023-11-02', TRUE, 'Graft appears to be taking well.'),
('Fetal Non-Stress Test (NST)', 'Monitoring fetal heart rate and movement.', 280.00, 1, '2024-01-18', FALSE, 'Test reactive, indicating fetal well-being.'),
('Dental Implant Placement - Stage 1', 'Surgical placement of dental implant fixture.', 2200.00, 2, '2023-08-24', TRUE, 'Healing period required before next stage.'),
('Bronchoscopy with Biopsy', 'Endoscopic examination of airways with tissue sampling.', 2800.00, 1, '2024-02-23', TRUE, 'Biopsies taken from suspicious lesion.'),
('Grief Counseling Session', 'Therapy focused on processing loss.', 150.00, 1, '2023-11-16', TRUE, 'Patient expressing emotions related to bereavement.'),
('Orthotic Fitting and Dispensing', 'Measurement and provision of custom orthotics.', 450.00, 1, '2024-03-15', FALSE, 'Patient instructed on break-in period.'),
('HIV Test - Rapid Antibody', 'Rapid screening test for HIV antibodies.', 75.00, 0, '2023-10-26', FALSE, 'Result negative.'),
('Foreign Body Removal - Eye (Corneal)', 'Removal of small particle from the cornea.', 350.00, 0, '2024-01-30', TRUE, 'Antibiotic drops prescribed.'),
('Pacemaker Implantation', 'Surgical placement of cardiac pacemaker device.', 28000.00, 2, '2023-12-21', TRUE, 'Device programmed and functioning correctly.'),
('Speech Therapy - Articulation Drills', 'Practice exercises for specific speech sounds.', 150.00, 1, '2024-03-07', TRUE, 'Targeting /r/ sound production.'),
('Vaccination - HPV (Gardasil 9) - Dose 1', 'First dose of Human Papillomavirus vaccine.', 230.00, 0, '2023-09-14', TRUE, 'Recommended for cancer prevention.'),
('Thyroid Fine Needle Aspiration (FNA)', 'Biopsy of thyroid nodule using a fine needle.', 650.00, 1, '2024-01-16', TRUE, 'Sample sent for cytopathology.'),
('Thoracentesis', 'Procedure to remove fluid from space around lungs.', 950.00, 1, '2023-11-23', TRUE, 'Fluid sent for analysis.'),
('Acupressure Session', 'Application of pressure to specific body points.', 90.00, 1, '2024-03-08', TRUE, 'Focused on headache relief points.'),
('Intravenous Immunoglobulin (IVIG) Infusion', 'Administration of IVIG for autoimmune disorder.', 6000.00, 5, '2023-12-28', TRUE, 'Patient monitored closely for reactions.'),
('Knee Replacement - Total (TKR)', 'Surgical replacement of the knee joint.', 32000.00, 4, '2024-02-08', TRUE, 'Initiated post-op PT protocol.'),
('Nail Avulsion - Ingrown Toenail', 'Removal of part or all of toenail.', 350.00, 1, '2024-03-20', TRUE, 'Phenol applied to matrix.'),
('Stress Echocardiogram', 'Echocardiogram performed before and after exercise/stress.', 950.00, 2, '2023-11-07', FALSE, 'No wall motion abnormalities induced.'),
('Cognitive Behavioral Therapy (CBT) Session', 'Standard CBT session for anxiety.', 160.00, 1, '2024-01-23', TRUE, 'Reviewed thought records.'),
('Adenoidectomy', 'Surgical removal of adenoids.', 4500.00, 1, '2023-10-05', TRUE, 'Performed for chronic nasal obstruction.'),
('Laser Treatment - Retinal Tear', 'Laser procedure to seal a tear in the retina.', 1200.00, 1, '2023-11-28', TRUE, 'Patient advised on activity restrictions.'),
('Epidural Blood Patch', 'Procedure to treat post-lumbar puncture headache.', 700.00, 1, '2023-12-13', FALSE, 'Patient reported headache relief.'),
('TB Skin Test (PPD) Placement', 'Intradermal injection for tuberculosis screening.', 40.00, 0, '2024-02-15', TRUE, 'Instructed patient to return in 48-72 hours for reading.'),
('IUD Removal', 'Removal of intrauterine device.', 150.00, 0, '2024-02-07', FALSE, 'Removed without difficulty.'),
('Botox Injection - Migraine Prophylaxis', 'Injections into specific head/neck muscles.', 1100.00, 1, '2024-01-11', TRUE, 'Standard migraine protocol injections given.'),
('Dental Crown Lengthening', 'Surgical procedure to expose more tooth structure.', 750.00, 1, '2024-03-13', TRUE, 'Performed prior to final crown placement.'),
('Vaccination - Hepatitis B Series (Dose 2)', 'Second dose of Hepatitis B vaccine.', 70.00, 0, '2023-11-03', TRUE, 'Maintaining vaccination schedule.'),
('Laparotomy - Exploratory', 'Open surgical exploration of the abdomen.', 19000.00, 4, '2023-12-07', TRUE, 'Performed for unexplained abdominal pain.'),
('Play Therapy Session', 'Therapeutic use of play for child counseling.', 140.00, 1, '2024-02-22', TRUE, 'Child engaged well with therapist.'),
('Re-casting - Forearm Fracture', 'Removal of old cast and application of new one.', 400.00, 1, '2024-02-19', TRUE, 'Performed due to cast damage.'),
('Throat Culture - Rapid Strep Test', 'Swab collected to test for Strep A.', 35.00, 0, '2024-03-18', FALSE, 'Result negative.'),
('Breast Reconstruction - Implant Placement', 'Placement of breast implant after mastectomy.', 12000.00, 3, '2023-10-18', TRUE, 'Tissue expander removed, permanent implant placed.'),
('Phlebotomy for Therapeutic Hemochromatosis', 'Blood removal treatment for iron overload.', 120.00, 1, '2024-01-31', TRUE, 'Target ferritin levels discussed.'),
('Massage Therapy - Deep Tissue', 'Therapeutic massage focusing on deeper muscle layers.', 130.00, 1, '2023-12-27', FALSE, 'Patient reported muscle soreness relief.'),
('Tetanus Shot (Td)', 'Booster injection for tetanus and diphtheria.', 55.00, 0, '2024-02-26', FALSE, 'Given after minor injury.'),
('ERCP (Endoscopic Retrograde Cholangiopancreatography)', 'Procedure to examine bile/pancreatic ducts.', 4500.00, 2, '2023-11-09', TRUE, 'Stone removed from common bile duct.'),
('Dermatology Consult - Rash Evaluation', 'Specialist consultation for skin rash.', 260.00, 1, '2024-01-12', TRUE, 'Diagnosis confirmed, treatment plan provided.'),
('Carpal Tunnel Release Surgery', 'Surgical procedure to relieve pressure on median nerve.', 6500.00, 1, '2023-09-13', TRUE, 'Patient reported tingling improvement post-op.'),
-- Rows 201-300
INSERT INTO Treatments (TreatmentName, Description, Cost, DurationHours, DateAdministered, FollowUpRequired, Notes) VALUES
('Physical Therapy - Balance Training', 'Exercises to improve stability and prevent falls.', 175.00, 1, '2023-05-24', TRUE, 'Practiced single leg stance.'),
('Rotator Cuff Repair Surgery', 'Surgical repair of torn rotator cuff tendon(s).', 15000.00, 3, '2024-02-12', TRUE, 'Arm placed in abduction sling post-op.'),
('Chemotherapy - Cycle 3 (Doxorubicin)', 'Intravenous administration of Doxorubicin.', 3100.00, 4, '2023-11-29', TRUE, 'Cardiac monitoring performed prior to infusion.'),
('X-Ray - Knee (4 Views)', 'Weight-bearing and non-weight-bearing knee radiography.', 150.00, 0, '2024-03-08', FALSE, 'Moderate osteoarthritic changes noted.'),
('Dental Examination - Child Initial', 'First dental visit examination for young child.', 120.00, 1, '2023-09-19', FALSE, 'Familiarized child with dental office environment.'),
('Vaccination - Shingles (Shingrix) - Dose 1', 'First dose of recombinant zoster vaccine.', 210.00, 0, '2023-10-26', TRUE, 'Advised patient about potential side effects.'),
('Grief Counseling - Individual', 'One-on-one therapy session for bereavement.', 160.00, 1, '2024-03-15', TRUE, 'Explored stages of grief.'),
('Nail Bed Repair', 'Surgical repair of injury to the nail bed.', 480.00, 1, '2023-12-19', TRUE, 'Finger splinted after repair.'),
('MRI Scan - Cervical Spine (without contrast)', 'Magnetic resonance imaging of the neck.', 1600.00, 1, '2024-01-24', FALSE, 'Disc herniation noted at C5-C6.'),
('Medication Injection - Allergy Shot Build-up Phase', 'Increasing dose allergy immunotherapy injection.', 50.00, 0, '2023-08-30', TRUE, 'Patient tolerated increased dose well.'),
('Thyroidectomy - Partial', 'Surgical removal of part of the thyroid gland.', 13000.00, 3, '2023-08-03', TRUE, 'Performed for suspicious nodule.'),
('Physical Therapy - Manual Therapy (Joint Mobs)', 'Hands-on mobilization of stiff joints.', 185.00, 1, '2023-06-26', TRUE, 'Applied to thoracic spine.'),
('Capsule Endoscopy', 'Patient swallows camera pill to image small intestine.', 2100.00, 0, '2024-03-22', TRUE, 'Patient instructed on prep and procedure.'),
('Ultrasound - Thyroid Nodule Follow-up', 'Monitoring size of previously identified thyroid nodule.', 350.00, 0, '2023-12-01', FALSE, 'Nodule size stable compared to prior scan.'),
('Laceration Repair - Chin (Dermabond)', 'Closure of chin wound using skin adhesive.', 280.00, 0, '2024-01-22', FALSE, 'Advised on care of adhesive.'),
('Patch Testing - Allergy', 'Application of patches to test for contact allergens.', 450.00, 1, '2023-10-09', TRUE, 'Patches to be removed and read in 48 hours.'),
('Pulmonary Rehab Session', 'Supervised exercise and education for lung disease.', 140.00, 2, '2024-03-25', TRUE, 'Patient completed endurance exercises.'),
('Wound Culture Collection', 'Swab collected from wound bed for bacterial culture.', 80.00, 0, '2023-10-17', FALSE, 'Sample sent to microbiology lab.'),
('Dialectical Behavior Therapy (DBT) Skills Group', 'Group therapy session teaching DBT skills.', 90.00, 2, '2024-02-20', TRUE, 'Focused on mindfulness skills this week.'),
('Shoulder Injection - Subacromial (Cortisone)', 'Injection into space above rotator cuff.', 230.00, 0, '2024-01-09', TRUE, 'For treatment of bursitis/impingement.'),
('Biopsy - Endometrial', 'Sampling of uterine lining tissue.', 380.00, 0, '2024-02-09', TRUE, 'Performed for abnormal uterine bleeding.'),
('Radiation Therapy - Session 10', 'Ongoing radiation treatment administration.', 950.00, 1, '2023-09-07', TRUE, 'Skin reaction monitored.'),
('Crutch Fitting and Training', 'Proper fitting and instruction on crutch use.', 85.00, 0, '2024-03-19', FALSE, 'Patient demonstrated safe ambulation.'),
('Dental Cleaning - Deep (Scaling/Root Planing) Quad 1', 'Periodontal treatment for gum disease.', 350.00, 1, '2023-12-06', TRUE, 'Local anesthesia administered.'),
('Cardiac Rehabilitation Session', 'Monitored exercise session post-cardiac event.', 160.00, 1, '2024-02-28', TRUE, 'Patient ECG monitored during exercise.'),
('Diabetes - Insulin Pump Training', 'Education on use of insulin pump therapy.', 250.00, 2, '2023-10-31', TRUE, 'Patient practiced site insertion and bolusing.'),
('Staple Removal - Abdominal Incision', 'Removal of surgical staples from abdomen.', 90.00, 0, '2024-01-29', FALSE, 'Wound closed with Steri-strips after removal.'),
('Glucose Tolerance Test (OGTT)', 'Testing blood sugar response after glucose load.', 120.00, 3, '2023-09-25', FALSE, 'Performed for gestational diabetes screening.'),
('Central Line Removal', 'Removal of central venous catheter.', 150.00, 0, '2024-03-26', FALSE, 'Pressure held at site post-removal.'),
('Cast Application - Short Leg Walking Cast', 'Application of cast for lower leg/ankle fracture.', 420.00, 1, '2024-01-18', TRUE, 'Patient instructed on weight-bearing restrictions.'),
('Video Swallow Study (Modified Barium Swallow)', 'Radiographic study of swallowing function.', 600.00, 1, '2024-02-13', FALSE, 'Aspiration noted with thin liquids.'),
('Vaccination - Meningococcal ACWY', 'Administration of meningococcal vaccine.', 160.00, 0, '2023-08-22', FALSE, 'Required for college entry.'),
('Physical Therapy - Electrical Stimulation (TENS)', 'Application of transcutaneous electrical nerve stimulation.', 65.00, 0, '2024-03-02', TRUE, 'Used for pain management.'),
('Esophageal Manometry', 'Measurement of esophageal muscle pressures.', 800.00, 1, '2023-11-08', FALSE, 'Study completed to evaluate swallowing difficulty.'),
('CT Angiography - Pulmonary Arteries', 'CT scan to visualize pulmonary arteries (for PE).', 2100.00, 1, '2024-03-21', FALSE, 'No evidence of pulmonary embolism.'),
('Surgical Drain Management Teaching', 'Educating patient on how to care for surgical drain at home.', 70.00, 1, '2023-11-28', FALSE, 'Patient demonstrated understanding.'),
('Nerve Block - Occipital', 'Injection of anesthetic near occipital nerves for headache.', 450.00, 0, '2024-01-31', TRUE, 'Patient reported significant temporary relief.'),
('Periodontal Maintenance Cleaning', 'Ongoing cleaning for patients with history of gum disease.', 180.00, 1, '2023-10-03', TRUE, 'Pocket depths monitored.'),
('Laser Hair Removal Session - Small Area', 'Laser treatment for hair reduction.', 150.00, 1, '2024-03-09', TRUE, 'Patient advised on sun avoidance.'),
('Paracentesis', 'Procedure to remove fluid from the abdominal cavity.', 850.00, 1, '2023-12-26', TRUE, 'Fluid sent for cell count and analysis.'),
('Wound Vac Dressing Change', 'Changing dressing for negative pressure wound therapy.', 200.00, 1, '2024-01-25', TRUE, 'Granulation tissue noted in wound bed.'),
('Exercise Prescription Counseling', 'Developing a personalized exercise plan.', 120.00, 1, '2023-11-21', FALSE, 'Plan tailored to patient goals and limitations.'),
('Eye Movement Desensitization and Reprocessing (EMDR) Session', 'Psychotherapy technique for trauma.', 190.00, 1, '2024-03-28', TRUE, 'Patient processing traumatic event.'),
('Removal of Skin Lesion - Excisional Biopsy', 'Surgical removal of entire skin lesion.', 450.00, 1, '2023-09-05', TRUE, 'Closure with sutures.'),
('Colposcopy without Biopsy', 'Magnified examination of cervix.', 400.00, 1, '2024-03-06', FALSE, 'No concerning areas visualized.'),
('Fetal Biophysical Profile (BPP)', 'Ultrasound assessment of fetal well-being.', 420.00, 1, '2023-10-24', FALSE, 'Score 8/8, reassuring.'),
('Knee Replacement Revision Surgery', 'Surgical procedure to replace failed knee implant.', 45000.00, 5, '2023-09-27', TRUE, 'Complex procedure due to bone loss.'),
('Retinal Exam - Diabetic Screening', 'Dilated eye exam to screen for diabetic retinopathy.', 170.00, 1, '2024-02-08', FALSE, 'No retinopathy detected.'),
('Occupational Therapy - Activities of Daily Living (ADL) Training', 'Training to improve self-care skills.', 180.00, 1, '2024-02-20', TRUE, 'Practiced dressing techniques.'),
('Cardiac Event Monitor Data Interpretation', 'Physician review and interpretation of event monitor data.', 150.00, 0, '2023-12-08', FALSE, 'Report generated with findings.'),
('Prolotherapy Injection - Joint', 'Injection of solution to stimulate tissue repair.', 350.00, 0, '2024-03-18', TRUE, 'Performed on osteoarthritic knee.'),
('Sclerotherapy - Spider Vein Treatment', 'Injection of solution to collapse small veins.', 400.00, 1, '2023-12-21', TRUE, 'Compression stockings recommended post-procedure.'),
('Wound Closure using Steri-Strips', 'Application of adhesive strips to close small wound.', 60.00, 0, '2023-11-09', FALSE, 'Alternative to sutures for minor cuts.'),
('First Trimester Prenatal Screening Test', 'Blood test and ultrasound for chromosomal abnormalities.', 600.00, 1, '2024-01-25', FALSE, 'Results discussed with patient.'),
('Tooth Extraction - Complex Surgical', 'Surgical removal requiring bone removal or sectioning.', 650.00, 1, '2023-08-31', TRUE, 'Patient given pain medication prescription.'),
('Methacholine Challenge Test', 'Pulmonary function test to diagnose asthma.', 450.00, 2, '2024-02-27', FALSE, 'Test positive, indicating airway hyperreactivity.'),
('Dialectical Behavior Therapy (DBT) - Individual Session', 'One-on-one therapy using DBT principles.', 170.00, 1, '2023-11-23', TRUE, 'Focused on emotion regulation skills.'),
('Fitting for Compression Stockings', 'Measurement and selection of appropriate compression garments.', 75.00, 0, '2024-03-22', FALSE, 'Patient educated on proper application.'),
('Rapid Influenza Test', 'Swab collected for rapid flu diagnosis.', 50.00, 0, '2023-10-31', FALSE, 'Result positive for Influenza A.'),
('Foreign Body Removal - Nose', 'Extraction of foreign object from nasal passage.', 220.00, 0, '2024-02-05', FALSE, 'Small toy removed.'),
('Coronary Calcium Scan', 'CT scan to measure calcium deposits in heart arteries.', 350.00, 0, '2024-01-04', FALSE, 'Score calculated and reported.'),
('Biofeedback Training Session', 'Using electronic monitoring to learn control over body functions.', 150.00, 1, '2024-03-13', TRUE, 'Focused on muscle tension reduction.'),
('Vaccination - Rabies Post-Exposure Prophylaxis (Dose 1) + RIG', 'Initial treatment after potential rabies exposure.', 1800.00, 1, '2023-09-21', TRUE, 'Rabies Immune Globulin (RIG) administered around wound.'),
('Thyroid Lobectomy', 'Surgical removal of one lobe of the thyroid gland.', 12000.00, 2, '2024-01-23', TRUE, 'Pathology pending on removed lobe.'),
('Arthrocentesis - Shoulder', 'Aspiration of fluid from the shoulder joint.', 320.00, 0, '2023-11-30', TRUE, 'Fluid analysis ordered.'),
('Chiropractic Adjustment - Extremity', 'Manual manipulation of a joint other than the spine.', 75.00, 0, '2024-03-15', TRUE, 'Performed on ankle joint.'),
('Intravenous Antibiotic Therapy - Home Infusion Setup', 'Setup and patient training for home IV antibiotics.', 450.00, 2, '2024-01-03', TRUE, 'Nurse coordinated with home health agency.'),
('Hip Arthroscopy - Labral Repair', 'Minimally invasive surgery to repair hip labrum tear.', 16000.00, 3, '2024-02-14', TRUE, 'Weight-bearing restrictions post-op.'),
('Ingrown Toenail Partial Removal', 'Partial removal of nail plate for ingrown toenail.', 300.00, 1, '2024-03-27', TRUE, 'Antibiotic ointment applied.'),
('Transesophageal Echocardiogram (TEE)', 'Ultrasound of heart using probe placed in esophagus.', 1500.00, 1, '2023-11-15', FALSE, 'Performed under sedation.'),
('Exposure and Response Prevention (ERP) Therapy Session', 'Therapy technique for OCD.', 180.00, 1, '2024-01-30', TRUE, 'Patient worked on hierarchy of feared situations.'),
('Nephrectomy - Partial Laparoscopic', 'Surgical removal of part of a kidney.', 28000.00, 4, '2023-10-12', TRUE, 'Performed for small renal mass.'),
('Optical Coherence Tomography (OCT) - Eye', 'Imaging of retinal layers.', 250.00, 0, '2023-12-05', FALSE, 'Scan normal.'),
('Trigger Finger Release Surgery', 'Surgical procedure to treat trigger finger.', 3500.00, 1, '2024-01-18', TRUE, 'Patient advised on hand exercises post-op.'),
('Tuberculosis Blood Test (IGRA)', 'Blood test (e.g., QuantiFERON) for TB screening.', 120.00, 0, '2024-02-20', FALSE, 'Blood sample sent to lab.'),
('Nexplanon Insertion', 'Placement of subdermal contraceptive implant.', 480.00, 0, '2024-02-14', FALSE, 'Implant placed in non-dominant arm.'),
('Facet Joint Injection - Lumbar', 'Injection into small joints of the spine for pain.', 750.00, 1, '2024-01-19', TRUE, 'Performed bilaterally at L4-L5.'),
('Dental Implant Restoration (Crown Placement)', 'Placement of crown onto dental implant.', 1600.00, 1, '2024-03-20', FALSE, 'Final restoration completed.'),
('Vaccination - Pneumococcal (PPSV23)', 'Administration of pneumococcal polysaccharide vaccine.', 110.00, 0, '2023-11-10', FALSE, 'Recommended for adults over 65 or with risk factors.'),
('Prostatectomy - Robotic Assisted Laparoscopic', 'Surgical removal of the prostate gland.', 38000.00, 5, '2023-12-14', TRUE, 'Catheter placed post-operatively.'),
('Hypnotherapy Session', 'Therapy utilizing hypnosis techniques.', 170.00, 1, '2024-02-29', TRUE, 'Focused on smoking cessation.'),
('Orthopedic Casting - Long Arm Cast', 'Application of cast from upper arm to hand.', 480.00, 1, '2024-03-01', TRUE, 'For treatment of humerus fracture.'),
('Urine Culture and Sensitivity', 'Laboratory test to identify bacteria in urine.', 75.00, 0, '2024-03-25', FALSE, 'Performed if initial urinalysis suggests infection.'),
('Lumpectomy - Breast Cancer', 'Surgical removal of cancerous lump from breast.', 11000.00, 2, '2023-10-25', TRUE, 'Margins assessed during procedure.'),
('Blood Glucose Monitoring Training', 'Educating patient on using a glucometer.', 60.00, 1, '2024-02-07', TRUE, 'Patient demonstrated correct usage.'),
('Craniotomy for Tumor Resection', 'Open brain surgery to remove tumor.', 95000.00, 7, '2024-01-10', TRUE, 'Patient monitored in neuro ICU post-op.'),
('Antibiotic Sensitivity Testing', 'Lab test determining antibiotic effectiveness against bacteria.', 90.00, 0, '2023-10-18', FALSE, 'Performed on cultured organism.'),
('Video EEG Monitoring (Inpatient)', 'Continuous EEG monitoring over several days.', 4500.00, 72, '2024-01-26', TRUE, 'Performed to capture seizure activity.'),
('Cardiology Consult - Arrhythmia', 'Specialist consultation for irregular heartbeat.', 280.00, 1, '2024-01-17', TRUE, 'Recommended further testing.'),
('Bunionectomy', 'Surgical correction of bunion deformity.', 8000.00, 2, '2023-09-20', TRUE, 'Patient placed in surgical shoe.'),
-- Rows 301-400
INSERT INTO Treatments (TreatmentName, Description, Cost, DurationHours, DateAdministered, FollowUpRequired, Notes) VALUES
('Physical Therapy - Aquatic Therapy Session', 'Exercises performed in a pool.', 190.00, 1, '2023-05-31', TRUE, 'Reduces joint stress during exercise.'),
('Spinal Fusion Surgery - Lumbar', 'Joining two or more vertebrae in the lower back.', 65000.00, 5, '2024-02-19', TRUE, 'Bone graft material used.'),
('Chemotherapy - Cycle 4 (Carboplatin)', 'Intravenous administration of Carboplatin.', 2950.00, 4, '2023-12-13', TRUE, 'Pre-medications given for hypersensitivity prevention.'),
('X-Ray - Sinuses', 'Radiography of the paranasal sinuses.', 110.00, 0, '2024-03-15', FALSE, 'Findings consistent with sinusitis.'),
('Fluoride Varnish Application - Child', 'Topical fluoride treatment for cavity prevention.', 45.00, 0, '2023-09-26', FALSE, 'Applied after cleaning.'),
('Vaccination - Shingles (Shingrix) - Dose 2', 'Second dose of recombinant zoster vaccine.', 210.00, 0, '2023-12-21', FALSE, 'Completes the vaccine series.'),
('Family Counseling - Parenting Skills', 'Therapy focused on improving parenting strategies.', 180.00, 1, '2024-03-22', TRUE, 'Discussed positive reinforcement techniques.'),
('Foreign Body Removal - Skin (Splinter)', 'Extraction of splinter embedded in skin.', 120.00, 0, '2023-12-26', FALSE, 'Small splinter removed with forceps.'),
('MRI Scan - Knee (with arthrogram)', 'MRI after injecting contrast into knee joint.', 2100.00, 2, '2024-01-31', FALSE, 'Helps visualize internal joint structures like labrum/cartilage.'),
('Medication Injection - Depo-Provera', 'Intramuscular injection for contraception.', 85.00, 0, '2023-09-06', TRUE, 'Administered every 3 months.'),
('Parathyroidectomy', 'Surgical removal of one or more parathyroid glands.', 14500.00, 3, '2023-08-10', TRUE, 'Performed for hyperparathyroidism.'),
('Physical Therapy - Traction (Cervical)', 'Mechanical traction applied to the neck.', 90.00, 0, '2023-07-03', TRUE, 'Used for nerve root impingement.'),
('Bravo pH Monitoring Capsule Placement', 'Endoscopic placement of capsule to measure esophageal pH.', 1600.00, 1, '2024-03-29', TRUE, 'Patient wears receiver to record data.'),
('Ultrasound - Carotid Arteries', 'Imaging of arteries in the neck for stenosis.', 420.00, 1, '2023-12-08', FALSE, 'Mild plaque noted, no significant stenosis.'),
('Laceration Repair - Lip (Absorbable Sutures)', 'Closure of lip wound using dissolving stitches.', 340.00, 1, '2024-02-01', FALSE, 'Careful alignment of vermillion border.'),
('Allergy Blood Test (RAST/ImmunoCAP)', 'Blood test measuring specific IgE antibodies.', 400.00, 0, '2023-10-16', FALSE, 'Alternative to skin prick testing.'),
('Cardiac Stress Test - Nuclear (Myocardial Perfusion Imaging)', 'Stress test combined with imaging using radioactive tracer.', 1800.00, 3, '2024-03-28', FALSE, 'Images acquired at rest and post-stress.'),
('Stool Test for Ova and Parasites', 'Laboratory examination of stool for parasites.', 95.00, 0, '2023-10-24', FALSE, 'Multiple samples may be required.'),
('Acceptance and Commitment Therapy (ACT) Session', 'Psychotherapy focusing on acceptance and values.', 170.00, 1, '2024-02-27', TRUE, 'Explored acceptance of difficult thoughts/feelings.'),
('Elbow Injection - Tennis Elbow (Cortisone)', 'Injection near lateral epicondyle for tendonitis.', 210.00, 0, '2024-01-16', TRUE, 'Advised rest and activity modification.'),
('Biopsy - Bone Marrow Aspiration and Biopsy', 'Collection of bone marrow sample from hip bone.', 1500.00, 1, '2024-02-16', TRUE, 'Performed under local anesthesia.'),
('Brachytherapy - Prostate Cancer', 'Placement of radioactive seeds into the prostate.', 18000.00, 2, '2023-09-14', TRUE, 'Internal radiation treatment.'),
('Shoulder Manipulation Under Anesthesia', 'Procedure to break up scar tissue in stiff shoulder.', 3500.00, 1, '2024-03-26', TRUE, 'Followed immediately by physical therapy.'),
('Dental Onlay Placement', 'Indirect restoration covering cusp(s) of tooth.', 950.00, 2, '2023-12-13', TRUE, 'More conservative than a full crown.'),
('Pulmonary Exercise Stress Test (CPET)', 'Detailed assessment of heart/lung function during exercise.', 750.00, 2, '2024-03-05', FALSE, 'Measures oxygen consumption and gas exchange.'),
('Mental Status Examination', 'Structured assessment of patient psychological function.', 100.00, 0, '2023-11-07', FALSE, 'Part of psychiatric evaluation.'),
('Drain Insertion - Pleural Effusion', 'Placement of chest tube to drain fluid around lung.', 1200.00, 1, '2024-02-06', TRUE, 'Connected to drainage system.'),
('Continuous Positive Airway Pressure (CPAP) Titration Study', 'Overnight study to determine optimal CPAP pressure.', 2300.00, 8, '2023-10-04', TRUE, 'Pressure adjusted throughout the night.'),
('Port-a-Cath Placement', 'Surgical insertion of implantable venous access port.', 2500.00, 1, '2024-03-30', TRUE, 'For long-term IV therapy like chemotherapy.'),
('Cast Adjustment/Wedging', 'Modification of existing cast to improve fracture alignment.', 150.00, 0, '2024-01-25', TRUE, 'Performed based on follow-up X-ray.'),
('Electrocautery for Skin Tag Removal', 'Using heat to destroy small skin tags.', 130.00, 0, '2024-02-20', FALSE, 'Performed under local anesthesia.'),
('Vaccination - Haemophilus influenzae type b (Hib)', 'Administration of Hib vaccine.', 80.00, 0, '2023-08-29', FALSE, 'Part of infant vaccination series.'),
('Physical Therapy - Dry Needling', 'Insertion of fine needles into trigger points.', 120.00, 0, '2024-03-09', TRUE, 'Used for myofascial pain relief.'),
('24-Hour Esophageal pH Monitoring', 'Measuring acid reflux into the esophagus over 24 hours.', 900.00, 1, '2023-11-15', FALSE, 'Probe placed through the nose.'),
('CT Urogram', 'CT scan specifically imaging the urinary tract.', 1850.00, 1, '2024-03-28', FALSE, 'Requires contrast injection.'),
('Wound Packing Removal', 'Taking out packing material from a drained wound.', 50.00, 0, '2023-11-30', TRUE, 'Wound assessed for healing progress.'),
('Botox Injection - Cosmetic (Forehead Lines)', 'Injection for temporary reduction of wrinkles.', 450.00, 0, '2024-02-07', FALSE, 'Patient advised results take several days.'),
('Gingivectomy', 'Surgical removal of gum tissue.', 600.00, 1, '2023-10-10', TRUE, 'Performed for periodontal health or aesthetics.'),
('Chemical Peel - Light (Glycolic Acid)', 'Application of chemical solution for skin exfoliation.', 180.00, 1, '2024-03-16', FALSE, 'Patient advised on post-peel care.'),
('Joint Mobilization - Ankle', 'Manual therapy technique to improve ankle mobility.', 80.00, 0, '2024-01-03', TRUE, 'Performed after cast removal.'),
('Wound Closure Assessment', 'Checking integrity of sutures/staples/adhesive.', 40.00, 0, '2024-01-30', FALSE, 'No signs of dehiscence.'),
('Stress Management Group Session', 'Group therapy focused on coping with stress.', 70.00, 2, '2023-11-28', TRUE, 'Practiced relaxation techniques.'),
('Electroconvulsive Therapy (ECT) Session', 'Brief electrical stimulation of the brain under anesthesia.', 1400.00, 2, '2024-03-31', TRUE, 'Performed for severe depression.'),
('Removal of Skin Lesion - Shave Biopsy', 'Thin slice of lesion removed for diagnosis.', 260.00, 0, '2023-09-12', TRUE, 'Hemostasis achieved with aluminum chloride.'),
('LEEP (Loop Electrosurgical Excision Procedure)', 'Removal of abnormal cervical tissue using heated wire loop.', 850.00, 1, '2024-03-13', TRUE, 'Specimen sent for pathology.'),
('Quadrivalent Influenza Vaccine High-Dose', 'Flu vaccine formulation for adults 65+.', 75.00, 0, '2023-10-31', FALSE, 'Higher antigen dose for better immune response.'),
('Shoulder Replacement - Reverse Total', 'Shoulder joint replacement for specific rotator cuff issues.', 38000.00, 4, '2023-10-04', TRUE, 'Different implant design than standard THR.'),
('Visual Field Test (Perimetry)', 'Mapping the scope of vision.', 180.00, 1, '2024-02-15', FALSE, 'Performed to check for glaucoma progression or neurological issues.'),
('Occupational Therapy - Ergonomic Assessment', 'Evaluation of workspace setup.', 200.00, 1, '2024-02-27', FALSE, 'Recommendations provided to reduce strain.'),
('Ambulatory Blood Pressure Monitoring (24hr)', 'Wearing device to record BP over 24 hours.', 350.00, 0, '2023-12-15', TRUE, 'Device applied and patient instructed.'),
('Allergen Immunotherapy - Dose Adjustment', 'Modifying dose based on patient reaction/progress.', 0.00, 0, '2024-03-25', TRUE, 'Dose slightly increased.'),
('Cryoablation - Tumor Treatment', 'Using extreme cold to destroy tumor tissue.', 9000.00, 2, '2023-12-28', TRUE, 'Performed percutaneously under imaging guidance.'),
('Burn Debridement - Enzymatic', 'Using chemical agent to remove dead tissue from burn.', 350.00, 1, '2024-01-03', TRUE, 'Applied enzymatic ointment and dressed wound.'),
('Genetic Counseling Session', 'Discussion of genetic risks and testing options.', 300.00, 1, '2024-02-01', FALSE, 'Family history reviewed in detail.'),
('Dental Veneer Placement - Single Tooth', 'Application of thin porcelain shell to front of tooth.', 1300.00, 2, '2023-09-07', FALSE, 'Color match confirmed.'),
('Six-Minute Walk Test', 'Assessment of exercise capacity.', 150.00, 0, '2024-03-07', FALSE, 'Distance walked and oxygen saturation recorded.'),
('Eye Muscle Surgery (Strabismus Repair)', 'Surgical correction of misaligned eyes.', 7000.00, 2, '2023-11-30', TRUE, 'Performed on pediatric patient.'),
('Myringotomy with Tube Placement', 'Incision in eardrum and placement of ventilation tube.', 2500.00, 1, '2024-03-20', TRUE, 'Performed for recurrent ear infections.'),
('Nerve Biopsy', 'Surgical removal of small piece of nerve for analysis.', 2800.00, 1, '2024-01-24', TRUE, 'Typically performed on sural nerve in ankle.'),
('IV Iron Infusion', 'Intravenous administration of iron supplement.', 450.00, 2, '2024-02-02', TRUE, 'For treatment of iron deficiency anemia unresponsive to oral iron.'),
('Spinal Cord Stimulator Trial Placement', 'Temporary placement of electrodes near spinal cord for pain.', 6000.00, 2, '2024-02-13', TRUE, 'Patient evaluates effectiveness over trial period.'),
('Hemorrhoidectomy', 'Surgical removal of hemorrhoids.', 5500.00, 1, '2023-10-19', TRUE, 'Patient advised on post-op sitz baths.'),
('Fundoplication - Laparoscopic', 'Surgery to treat GERD by wrapping stomach around esophagus.', 19000.00, 3, '2024-01-11', TRUE, 'Patient started on liquid diet post-op.'),
('Electroretinogram (ERG)', 'Measurement of electrical response of the retina to light.', 700.00, 1, '2023-12-12', FALSE, 'Helps diagnose retinal disorders.'),
('Functional Capacity Evaluation (FCE)', 'Comprehensive assessment of work-related physical abilities.', 950.00, 4, '2024-03-01', FALSE, 'Often used for disability or return-to-work evaluations.'),
('Vaccination - Rotavirus (Oral)', 'Oral vaccine administration for infants.', 110.00, 0, '2023-09-06', FALSE, 'Given during well-child visit.'),
('Tracheostomy Tube Change', 'Replacement of existing tracheostomy tube.', 300.00, 0, '2024-02-09', TRUE, 'Performed routinely or if tube is malfunctioning.'),
('Arthrogram - Shoulder (MRI Contrast Injection)', 'Injection of contrast into shoulder joint prior to MRI.', 400.00, 1, '2024-01-26', FALSE, 'Performed under fluoroscopy.'),
('Manual Lymphatic Drainage Massage', 'Gentle massage technique to reduce lymphedema.', 140.00, 1, '2024-03-08', TRUE, 'Performed by certified therapist.'),
('PICC Line Placement', 'Insertion of peripherally inserted central catheter.', 1100.00, 1, '2024-01-17', TRUE, 'For intermediate-term IV access.'),
('Ankle Fusion (Arthrodesis)', 'Surgical fusion of the ankle joint.', 22000.00, 3, '2023-11-16', TRUE, 'Performed for severe arthritis.'),
('Refractive Eye Exam', 'Exam specifically to determine glasses/contact lens prescription.', 95.00, 1, '2024-02-21', FALSE, 'Patient updated prescription.'),
('Septoplasty', 'Surgical correction of deviated nasal septum.', 6800.00, 1, '2023-10-26', TRUE, 'Nasal packing may be used post-op.'),
('Intravitreal Injection - Eye', 'Injection of medication directly into the eye vitreous.', 650.00, 0, '2024-01-05', TRUE, 'Common treatment for macular degeneration.'),
('Ganglion Cyst Aspiration/Injection', 'Draining fluid from cyst and possibly injecting steroid.', 280.00, 0, '2024-03-14', TRUE, 'Cyst may recur.'),
('Elective Cardioversion', 'Scheduled procedure to restore normal heart rhythm using electricity.', 2200.00, 1, '2023-12-20', TRUE, 'Performed under sedation.'),
('Pessary Fitting and Placement', 'Fitting and insertion of device to support pelvic organs.', 180.00, 1, '2024-02-28', TRUE, 'Patient instructed on removal and cleaning.'),
('Voice Therapy Session', 'Therapy to improve voice quality or function.', 150.00, 1, '2024-03-27', TRUE, 'Working on vocal hygiene techniques.'),
('Vaccination - Polio (IPV)', 'Inactivated polio vaccine injection.', 65.00, 0, '2023-09-13', FALSE, 'Part of standard childhood series.'),
('Feeding Tube Placement - PEG (Percutaneous Endoscopic Gastrostomy)', 'Endoscopic placement of feeding tube into stomach.', 3500.00, 1, '2024-01-09', TRUE, 'Provides long-term nutritional support.'),
('Shoulder Arthroscopy - Decompression', 'Minimally invasive surgery to relieve shoulder impingement.', 8000.00, 1, '2024-02-16', TRUE, 'Subacromial bone spur removed.'),
('Light Therapy for Seasonal Affective Disorder (SAD)', 'Exposure to bright light box.', 75.00, 1, '2023-11-24', TRUE, 'Patient instructed on daily use during winter months.'),
('PICC Line Removal', 'Removal of peripherally inserted central catheter.', 120.00, 0, '2024-02-08', FALSE, 'Site dressing applied.'),
('Small Bowel Resection - Laparoscopic', 'Surgical removal of part of the small intestine.', 24000.00, 4, '2023-12-01', TRUE, 'Performed for Crohn disease complication.'),
('Cognitive Remediation Therapy', 'Therapy to improve cognitive skills like memory/attention.', 190.00, 1, '2024-03-06', TRUE, 'Utilized computer-based exercises.'),
('Spirometry - Home Monitoring Device Training', 'Teaching patient how to use home spirometer.', 90.00, 1, '2024-03-13', FALSE, 'Patient to track peak flows daily.'),
('Urine Drug Screen Collection', 'Collection of urine sample for drug testing.', 55.00, 0, '2024-03-29', FALSE, 'Chain of custody maintained if required.'),
('Sentinel Lymph Node Biopsy', 'Surgical biopsy of first lymph node(s) draining a tumor.', 4500.00, 1, '2023-10-30', TRUE, 'Performed during cancer surgery.'),
('Insulin Adjustment Call/Consult', 'Phone consultation to adjust insulin doses.', 50.00, 0, '2024-02-15', FALSE, 'Based on patient reported blood sugar levels.'),
('Liver Biopsy - Percutaneous', 'Needle biopsy of the liver through the skin.', 1800.00, 1, '2024-01-22', TRUE, 'Performed under ultrasound guidance.'),
('Hand Therapy - Post-Surgical Rehab', 'Specialized therapy after hand surgery.', 180.00, 1, '2024-01-25', TRUE, 'Focus on scar management and tendon gliding.'),
('Cervical Cerclage Placement', 'Surgical stitch placed in cervix during pregnancy.', 3800.00, 1, '2023-11-03', TRUE, 'To prevent preterm birth.'),
-- Rows 401-500
INSERT INTO Treatments (TreatmentName, Description, Cost, DurationHours, DateAdministered, FollowUpRequired, Notes) VALUES
('Physical Therapy - Vestibular Rehabilitation', 'Exercises for dizziness and balance disorders.', 180.00, 1, '2023-06-07', TRUE, 'Patient performed habituation exercises.'),
('Laminectomy - Lumbar', 'Surgery to remove lamina bone, relieving spinal nerve pressure.', 26000.00, 3, '2024-02-26', TRUE, 'Performed for spinal stenosis.'),
('Chemotherapy - Maintenance Phase', 'Lower dose or less frequent chemo to prevent recurrence.', 1800.00, 3, '2023-12-20', TRUE, 'Patient tolerating maintenance schedule.'),
('X-Ray - Hand (3 Views)', 'Radiography of the hand and wrist.', 125.00, 0, '2024-03-22', FALSE, 'No acute fracture or dislocation.'),
('Dental Impressions for Night Guard', 'Taking molds of teeth for custom bruxism appliance.', 150.00, 1, '2023-10-03', TRUE, 'Night guard fabricated by lab.'),
('Vaccination - Japanese Encephalitis', 'Vaccine for travelers to specific regions.', 350.00, 0, '2023-11-02', TRUE, 'Requires multiple doses.'),
('Motivational Interviewing Session', 'Counseling technique to enhance motivation for change.', 150.00, 1, '2024-03-29', TRUE, 'Focused on readiness for smoking cessation.'),
('Incision Care Instructions', 'Educating patient on how to care for surgical wound.', 40.00, 0, '2024-01-04', FALSE, 'Provided written instructions.'),
('MRI Scan - Abdomen (with contrast)', 'MRI imaging of abdominal organs.', 1900.00, 1, '2024-02-07', FALSE, 'Liver lesion characterized.'),
('Medication Injection - Prolia (Denosumab)', 'Subcutaneous injection for osteoporosis.', 1500.00, 0, '2023-09-13', TRUE, 'Administered every 6 months.'),
('Thyroid Storm Management (Inpatient)', 'Intensive treatment for severe hyperthyroidism.', 5000.00, 24, '2023-08-17', TRUE, 'Required ICU monitoring and multiple medications.'),
('Physical Therapy - McKenzie Method Assessment', 'Specific assessment protocol for back/neck pain.', 195.00, 1, '2023-07-10', TRUE, 'Identified directional preference.'),
('Endoscopic Ultrasound (EUS)', 'Ultrasound using probe on endoscope for detailed GI imaging.', 3200.00, 1, '2024-04-01', TRUE, 'Used to stage pancreatic tumor.'),
('Ultrasound - Renal (Kidneys)', 'Imaging of the kidneys and bladder.', 400.00, 1, '2023-12-15', FALSE, 'No hydronephrosis or masses seen.'),
('Abscess Packing Removal', 'Final removal of packing from healed abscess cavity.', 60.00, 0, '2024-02-08', FALSE, 'Wound healing by secondary intention.'),
('Food Allergy Oral Challenge', 'Controlled ingestion of potential food allergen under supervision.', 600.00, 4, '2023-10-23', TRUE, 'Challenge negative for peanut allergy.'),
('Transcranial Magnetic Stimulation (TMS) Session', 'Non-invasive brain stimulation for depression.', 450.00, 1, '2024-03-31', TRUE, 'Part of a series of treatments.'),
('Rapid Plasma Reagin (RPR) Test', 'Blood test screening for syphilis.', 45.00, 0, '2023-10-31', FALSE, 'Result non-reactive.'),
('Art Therapy Session', 'Using creative methods for therapeutic expression.', 130.00, 1, '2024-03-04', TRUE, 'Patient explored feelings through drawing.'),
('Plantar Fascia Injection (Cortisone)', 'Injection into the heel for plantar fasciitis.', 200.00, 0, '2024-01-23', TRUE, 'Advised limited weight bearing initially.'),
('Lymph Node Biopsy - Excisional', 'Surgical removal of entire lymph node.', 3200.00, 1, '2024-02-23', TRUE, 'Node sent for histological analysis.'),
('External Beam Radiation Therapy (EBRT) - Simulation', 'Planning session for external radiation.', 1600.00, 2, '2023-09-21', TRUE, 'Immobilization device created.'),
('Dynamic Gait Index Assessment', 'Test evaluating ability to modify balance during walking.', 90.00, 0, '2024-03-29', FALSE, 'Used in neurological or geriatric assessment.'),
('Dental Implant - Abutment Placement', 'Connecting piece placed on implant fixture.', 500.00, 1, '2023-12-20', TRUE, 'Prepares implant for final crown.'),
('Overnight Oximetry Study', 'Home monitoring of blood oxygen levels during sleep.', 250.00, 8, '2024-03-12', TRUE, 'Screening test for sleep apnea.'),
('Medication Education - New Anticoagulant', 'Teaching patient about new blood thinner medication.', 80.00, 1, '2023-11-14', TRUE, 'Reviewed dosing, side effects, interactions.'),
('Gastrostomy Tube (G-Tube) Replacement', 'Changing out an existing stomach feeding tube.', 450.00, 1, '2024-02-15', TRUE, 'Routine replacement or due to malfunction.'),
('CPAP Mask Fitting Session', 'Trying different masks to find best fit for CPAP therapy.', 100.00, 1, '2023-10-11', TRUE, 'Patient selected nasal pillow mask.'),
('Port-a-Cath Flush and Access', 'Accessing port and flushing with saline/heparin.', 90.00, 0, '2024-04-03', FALSE, 'Performed prior to chemotherapy infusion.'),
('Ankle Arthroscopy - Debridement', 'Minimally invasive surgery to clean out ankle joint.', 7800.00, 1, '2024-01-30', TRUE, 'Removed loose bodies and inflamed tissue.'),
('Laser Treatment - Tattoo Removal (Session 1)', 'First session of laser treatment to fade tattoo.', 300.00, 1, '2024-02-27', TRUE, 'Patient advised multiple sessions needed.'),
('Radiofrequency Ablation - Nerve (Facet Joint)', 'Using heat from radio waves to deaden pain nerves.', 2800.00, 1, '2024-01-08', TRUE, 'For chronic back pain unresponsive to injections.'),
('Wound Measurement and Documentation', 'Recording size and characteristics of a wound.', 30.00, 0, '2024-02-01', FALSE, 'Used to track healing progress.'),
('Mindfulness Meditation Training Session', 'Teaching techniques for focused awareness.', 110.00, 1, '2023-12-04', TRUE, 'Practiced body scan meditation.'),
('Testosterone Pellet Insertion', 'Subcutaneous placement of testosterone pellets.', 750.00, 1, '2024-03-07', TRUE, 'Provides sustained hormone release.'),
('Removal of Cerclage Stitch', 'Removing stitch from cervix late in pregnancy.', 250.00, 0, '2023-11-10', FALSE, 'Usually done in office setting.'),
('Ultrasound Guided Biopsy - Breast', 'Needle biopsy performed using ultrasound guidance.', 1200.00, 1, '2023-11-01', TRUE, 'Targeted specific lesion seen on imaging.'),
('Total Parenteral Nutrition (TPN) Management (Inpatient)', 'Managing intravenous nutritional support.', 1000.00, 24, '2024-02-22', TRUE, 'Requires careful monitoring of labs and fluid balance.'),
('Kinesio Taping Application', 'Applying elastic therapeutic tape.', 50.00, 0, '2024-03-14', FALSE, 'Used for muscle support or lymphatic drainage.'),
('Vaccination - Yellow Fever', 'Vaccine required for travel to certain countries.', 190.00, 0, '2023-09-28', FALSE, 'International Certificate of Vaccination provided.'),
('Cystoscopy - Diagnostic', 'Endoscopic examination of the bladder.', 750.00, 1, '2024-01-19', FALSE, 'Performed to evaluate hematuria.'),
('Bariatric Surgery - Gastric Sleeve (Laparoscopic)', 'Surgical weight loss procedure removing part of stomach.', 26000.00, 3, '2023-11-22', TRUE, 'Requires significant lifestyle changes post-op.'),
('Music Therapy Session', 'Using music interventions for therapeutic goals.', 120.00, 1, '2024-03-21', TRUE, 'Patient participated in receptive music listening.'),
('Bone Scan - Nuclear Medicine', 'Imaging scan using radioactive tracer to detect bone abnormalities.', 850.00, 3, '2024-02-05', FALSE, 'Used to screen for bone metastases or infection.'),
('Pessary Cleaning and Reinsertion', 'Removing, cleaning, and replacing vaginal pessary.', 90.00, 0, '2024-03-06', TRUE, 'Routine maintenance visit.'),
('Swallowing Therapy Session', 'Exercises to improve swallowing function.', 160.00, 1, '2024-03-28', TRUE, 'Practiced Mendelsohn maneuver.'),
('Vaccination - DTaP (Childhood)', 'Diphtheria, tetanus, acellular pertussis vaccine.', 75.00, 0, '2023-09-20', FALSE, 'Part of routine infant/child series.'),
('Gastrostomy Tube Site Care Teaching', 'Educating patient/caregiver on cleaning G-tube site.', 65.00, 1, '2024-01-16', FALSE, 'Demonstrated proper technique.'),
('Hip Arthroscopy - FAI Correction', 'Minimally invasive surgery to correct hip impingement.', 17000.00, 3, '2024-02-21', TRUE, 'Reshaped femoral head/acetabulum.'),
('Bio-Identical Hormone Replacement Therapy Consult', 'Discussion regarding specific hormone preparations.', 250.00, 1, '2023-11-29', TRUE, 'Saliva/blood tests ordered.'),
('Home Sleep Apnea Test (HSAT) Dispensing', 'Providing device and instructions for home sleep study.', 300.00, 1, '2023-10-18', TRUE, 'Patient to return device after use.'),
('Colostomy Reversal Surgery', 'Surgical procedure to reconnect bowel after colostomy.', 21000.00, 4, '2024-01-15', TRUE, 'Patient monitored for bowel function return.'),
('Dialysis Access Fistula Maturation Check', 'Assessing readiness of AV fistula for dialysis use.', 100.00, 0, '2024-03-19', FALSE, 'Ultrasound may be used.'),
('Urine Pregnancy Test', 'Testing urine sample for hCG.', 25.00, 0, '2024-04-02', FALSE, 'Result obtained quickly.'),
('Mohs Surgery - Skin Cancer Removal (Stage 1)', 'Microscopic surgery removing skin cancer layer by layer.', 2500.00, 2, '2023-11-08', TRUE, 'First layer removed and examined.'),
('Long Term EEG Monitoring Review', 'Physician interpretation of extended EEG recording.', 350.00, 1, '2024-02-09', FALSE, 'Report details findings and clinical correlation.'),
('Pulmonary Consultation - Interstitial Lung Disease', 'Specialist evaluation for complex lung condition.', 300.00, 1, '2024-01-29', TRUE, 'Reviewed imaging and PFTs.'),
('Achilles Tendon Repair Surgery', 'Surgical repair of ruptured Achilles tendon.', 11000.00, 2, '2024-01-31', TRUE, 'Leg immobilized in cast/boot post-op.'),
('Cervical Ripening - Foley Bulb Placement', 'Mechanical method to help prepare cervix for labor induction.', 400.00, 1, '2023-11-17', TRUE, 'Patient admitted for induction process.'),
('Platelet Rich Plasma (PRP) Injection - Joint', 'Injection of concentrated platelets for healing.', 800.00, 1, '2024-03-11', TRUE, 'Used for osteoarthritis or tendon injury.'),
('Skin Lesion Cryotherapy - Actinic Keratosis', 'Freezing pre-cancerous skin lesions.', 110.00, 0, '2024-02-29', TRUE, 'Multiple lesions treated.'),
('Implantable Loop Recorder (ILR) Placement', 'Subcutaneous insertion of long-term heart monitor.', 3800.00, 1, '2024-01-24', TRUE, 'For diagnosing infrequent arrhythmias.'),
('Dental Whitening - In-Office Procedure', 'Professional teeth whitening treatment.', 500.00, 2, '2024-03-27', FALSE, 'Patient advised on avoiding staining foods.'),
('Vaccination - Rabies Pre-Exposure Prophylaxis (Dose 1)', 'First dose for individuals at high risk of rabies exposure.', 400.00, 0, '2023-10-12', TRUE, 'Series required for full protection.'),
('Colectomy - Laparoscopic Segmental', 'Surgical removal of a segment of the colon.', 27000.00, 4, '2024-01-04', TRUE, 'Performed for diverticular disease complication.'),
('Neuropsychological Testing Battery', 'Comprehensive testing of cognitive functions.', 2000.00, 6, '2024-03-04', TRUE, 'Assesses memory, attention, executive function, etc.'),
('Wheelchair Seating Evaluation', 'Assessment for appropriate wheelchair and seating system.', 250.00, 1, '2024-03-18', FALSE, 'Recommendations made for custom features.'),
('Glucose Challenge Test (Gestational Diabetes Screen)', 'Initial screening test during pregnancy.', 70.00, 1, '2023-10-05', FALSE, 'Blood drawn 1 hour after glucose drink.'),
('Breast Cyst Aspiration', 'Needle drainage of fluid-filled breast cyst.', 350.00, 0, '2023-11-21', TRUE, 'Fluid may be sent for cytology if suspicious.'),
('Home Health Nursing Visit Coordination', 'Arranging for nursing visits at patient home.', 75.00, 0, '2024-02-13', FALSE, 'Faxed orders to home health agency.'),
('Massage - Prenatal', 'Therapeutic massage adapted for pregnant individuals.', 140.00, 1, '2024-01-10', FALSE, 'Patient positioned for comfort and safety.'),
('Prothrombin Time/INR Check', 'Blood test monitoring warfarin effectiveness.', 35.00, 0, '2024-03-26', TRUE, 'INR result used for dose adjustment.'),
('Esophagogastroduodenoscopy (EGD) with Dilation', 'Upper endoscopy with stretching of esophageal narrowing.', 1600.00, 1, '2023-11-28', TRUE, 'Performed for dysphagia.'),
('Cardiology Follow-up - Post Stent', 'Check-up visit after coronary artery stent placement.', 180.00, 1, '2024-02-01', TRUE, 'Reviewed medications and symptoms.'),
('Tympanoplasty', 'Surgical repair of perforated eardrum.', 7200.00, 2, '2023-10-19', TRUE, 'Ear packing placed post-operatively.'),
('Physical Therapy - Post-Hip Replacement', 'Exercises focused on regaining hip mobility and strength.', 180.00, 1, '2023-06-14', TRUE, 'Patient ambulating with walker, working on transfers.'),
('Discectomy - Microscopic Lumbar', 'Minimally invasive surgery to remove herniated disc material.', 24000.00, 2, '2024-03-04', TRUE, 'Patient reported immediate relief of leg pain.'),
('Immunotherapy - Allergy Shot Maintenance', 'Regular injection to maintain desensitization.', 55.00, 0, '2024-01-08', TRUE, 'Patient tolerated dose well, no local reaction.'),
('X-Ray - Foot (3 Views)', 'Radiography of the foot.', 130.00, 0, '2024-04-01', FALSE, 'Evaluation for possible stress fracture.'),
('Dental Bonding - Anterior Tooth Chip', 'Application of composite resin to repair chipped tooth.', 350.00, 1, '2023-10-10', FALSE, 'Color matched to adjacent teeth.'),
('Vaccination - Typhoid Vi', 'Vaccine for travelers to areas where typhoid fever is common.', 110.00, 0, '2023-11-09', FALSE, 'Single dose injection.'),
('Cognitive Processing Therapy (CPT) Session', 'Therapy for PTSD focusing on challenging maladaptive thoughts.', 175.00, 1, '2024-04-04', TRUE, 'Patient worked on impact statement.'),
('Burn Dressing Application - Hydrocolloid', 'Application of specialized dressing for moist wound healing.', 70.00, 0, '2024-01-11', TRUE, 'Promotes autolytic debridement.'),
('MRI Scan - Shoulder (without contrast)', 'MRI imaging of the shoulder joint.', 1700.00, 1, '2024-02-14', FALSE, 'Findings consistent with rotator cuff tear.'),
('Medication Injection - Lupron Depot (GnRH agonist)', 'Injection for hormone therapy (e.g., prostate cancer, endometriosis).', 950.00, 0, '2023-09-20', TRUE, 'Long-acting formulation.'),
('Adrenalectomy - Laparoscopic', 'Surgical removal of an adrenal gland.', 21000.00, 3, '2023-08-24', TRUE, 'Performed for hormone-secreting tumor.'),
('Physical Therapy - Pilates-Based Rehab', 'Core strengthening exercises using Pilates principles.', 180.00, 1, '2023-07-17', TRUE, 'Focus on pelvic stability.'),
('Small Bowel Follow-Through (SBFT)', 'X-ray examination of the small intestine using barium.', 650.00, 3, '2024-04-05', FALSE, 'Images taken at timed intervals.'),
('Ultrasound - Testicular', 'Imaging of the testicles and scrotum.', 380.00, 0, '2023-12-22', FALSE, 'Evaluation for mass or torsion.'),
('Fish Hook Removal', 'Extraction of embedded fish hook.', 180.00, 0, '2024-02-15', FALSE, 'Removed using string-pull technique.'),
('Intradermal Allergy Testing', 'Injection of small amounts of allergens under the skin.', 420.00, 1, '2023-10-30', TRUE, 'More sensitive than skin prick testing.'),
('Ambulatory EEG Monitoring (48hr)', 'Extended EEG recording performed at home.', 1500.00, 0, '2024-04-02', TRUE, 'Patient diary reviewed along with EEG data.'),
('H. pylori Breath Test', 'Non-invasive test for Helicobacter pylori infection.', 150.00, 1, '2023-11-01', FALSE, 'Patient followed pre-test dietary instructions.'),
('Interpersonal Therapy (IPT) Session', 'Psychotherapy focusing on interpersonal relationships.', 165.00, 1, '2024-03-05', TRUE, 'Discussed recent conflict with family member.'),
('Sacroiliac (SI) Joint Injection', 'Injection into the SI joint for pain diagnosis/relief.', 650.00, 1, '2024-01-30', TRUE, 'Performed under fluoroscopy.'),
('Biopsy - Lymph Node Needle Aspiration', 'Using needle to collect cells from lymph node.', 500.00, 0, '2024-02-28', TRUE, 'Sample sent for cytology.'),
('Stereotactic Radiosurgery (SRS) - Brain Metastasis', 'Highly focused radiation dose to brain tumor.', 22000.00, 4, '2023-09-28', TRUE, 'Single high-dose session.'),
('Ankle Brace Fitting', 'Selection and fitting of appropriate ankle support brace.', 90.00, 0, '2024-04-01', FALSE, 'Patient demonstrated proper application.'),
('Dental Veneer Try-in', 'Checking fit and aesthetics of veneers before final cementation.', 100.00, 1, '2023-12-27', TRUE, 'Minor adjustments made.'),
('Methotrexate Injection - Ectopic Pregnancy', 'Medical treatment for early ectopic pregnancy.', 350.00, 1, '2024-03-12', TRUE, 'Requires monitoring of hCG levels.'),
('Diabetic Retinopathy Laser Treatment (PRP)', 'Pan-retinal photocoagulation laser therapy.', 1400.00, 1, '2023-11-16', TRUE, 'Performed in multiple sessions.'),
('Suture Removal - Knee Incision', 'Removing stitches from knee surgery wound.', 80.00, 0, '2024-02-13', FALSE, 'Wound healing well.'),
('Fecal Immunochemical Test (FIT) Kit Dispense', 'Providing kit for stool-based colorectal cancer screen.', 30.00, 0, '2023-10-06', FALSE, 'More specific than guaiac-based FOBT.'),
('Chest Tube Removal', 'Removal of tube draining pleural space.', 200.00, 0, '2024-03-31', FALSE, 'Follow-up chest X-ray performed.'),
('Orthopedic Boot Adjustment', 'Modifying fit or adding padding to walking boot.', 60.00, 0, '2024-02-02', FALSE, 'Ensured proper fit and comfort.'),
('Nasal Endoscopy', 'Examination of nasal passages and sinuses with endoscope.', 450.00, 0, '2024-02-26', FALSE, 'Performed in office for chronic sinusitis evaluation.'),
('Vaccination - Hepatitis A Series (Dose 1)', 'First dose of Hepatitis A vaccine.', 85.00, 0, '2023-09-05', TRUE, 'Recommended for travelers or high-risk groups.'),
('Manual Therapy - Soft Tissue Mobilization', 'Hands-on techniques to treat muscle/fascia restrictions.', 110.00, 1, '2024-03-16', TRUE, 'Applied to shoulder girdle.'),
('Barium Enema (Lower GI Series)', 'X-ray examination of the large intestine using barium contrast.', 750.00, 2, '2023-11-22', FALSE, 'Air contrast technique used.'),
('CT Myelogram', 'CT scan performed after contrast injected into spinal canal.', 2400.00, 2, '2024-04-04', FALSE, 'Detailed imaging of spinal cord and nerves.'),
('Surgical Debridement - Diabetic Foot Ulcer', 'Removal of dead tissue from foot wound.', 600.00, 1, '2024-01-12', TRUE, 'Offloading instructions reinforced.'),
('Lidocaine Patch Application/Prescription', 'Prescribing topical anesthetic patch for localized pain.', 45.00, 0, '2024-02-15', TRUE, 'Used for post-herpetic neuralgia.'),
('Crown Lengthening - Aesthetic', 'Surgical procedure to expose more tooth for cosmetic reasons.', 800.00, 1, '2023-10-17', TRUE, 'To improve smile appearance.'),
('Microdermabrasion Treatment', 'Mechanical exfoliation of the skin surface.', 160.00, 1, '2024-03-23', FALSE, 'Patient reported smoother skin texture.'),
('Lumbar Sympathetic Block', 'Injection targeting sympathetic nerves for leg pain/CRPS.', 900.00, 1, '2024-01-10', TRUE, 'Diagnostic and potentially therapeutic block.'),
('Feeding Evaluation - Pediatric', 'Assessment of child feeding skills and difficulties.', 220.00, 1, '2023-11-30', TRUE, 'Observed mealtime behaviors.'),
('Cognitive Screening Test (e.g., SLUMS, MoCA)', 'Brief office-based test of cognitive function.', 60.00, 0, '2024-01-05', FALSE, 'Score recorded in patient chart.'),
('Transcranial Doppler (TCD) Ultrasound', 'Ultrasound measuring blood flow velocity in brain arteries.', 550.00, 1, '2024-03-13', FALSE, 'Screening for vasospasm or stenosis.'),
('Removal of Sebaceous Cyst - Excision', 'Surgical removal of skin cyst.', 480.00, 1, '2023-09-19', TRUE, 'Entire cyst capsule removed to prevent recurrence.'),
('Endoscopic Retrograde Cholangiopancreatography (ERCP) with Stent Placement', 'ERCP procedure including placing stent in bile/pancreatic duct.', 5200.00, 2, '2023-12-07', TRUE, 'Stent placed to relieve obstruction.'),
('Zoster Vaccine (Shingrix) - Dose 2 Reminder Call', 'Phone call reminder for patient to receive second dose.', 0.00, 0, '2024-01-02', FALSE, 'Documented call in chart.'),
('Ankle Replacement Surgery - Total (TAA)', 'Surgical replacement of the ankle joint.', 34000.00, 4, '2023-10-11', TRUE, 'Less common than hip/knee replacement.'),
('Contact Lens Fitting - Toric Lenses', 'Fitting for contact lenses correcting astigmatism.', 180.00, 1, '2024-02-28', TRUE, 'Trial lenses dispensed.'),
('Occupational Therapy - Adaptive Equipment Training', 'Teaching use of devices like reachers, sock aids.', 150.00, 1, '2024-03-07', TRUE, 'Improved patient independence in ADLs.'),
('Implantable Cardioverter-Defibrillator (ICD) Interrogation', 'Checking function and data from implanted defibrillator.', 250.00, 0, '2023-12-22', TRUE, 'Device functioning normally, no arrhythmias detected.'),
('Growth Hormone Stimulation Test', 'Test assessing growth hormone production.', 900.00, 4, '2024-03-21', FALSE, 'Involves medication administration and timed blood draws.'),
('Sclerotherapy - Varicose Vein Treatment', 'Injection treatment for larger varicose veins.', 600.00, 1, '2024-01-03', TRUE, 'Multiple sessions often required.'),
('Skin Biopsy - Deep Shave/Saucerization', 'Biopsy technique removing deeper portion of lesion.', 300.00, 0, '2023-11-16', TRUE, 'Useful for suspected melanoma.'),
('Chorionic Villus Sampling (CVS)', 'Prenatal test sampling placental tissue.', 1600.00, 1, '2024-02-01', TRUE, 'Performed earlier in pregnancy than amniocentesis.'),
('Dental Bridge Cementation', 'Final placement and bonding of dental bridge.', 400.00, 1, '2023-10-04', FALSE, 'Patient advised on cleaning under bridge.'),
('Pulmonary Function Test - Lung Volumes', 'Measurement of total lung capacity and residual volume.', 250.00, 1, '2024-03-14', FALSE, 'Requires body plethysmography box.'),
('Hypnotherapy for Pain Management', 'Using hypnosis to alter perception of chronic pain.', 180.00, 1, '2024-01-18', TRUE, 'Patient reported moderate pain reduction during session.'),
('Orthotic Adjustment/Repair', 'Modifying existing orthotic device.', 80.00, 0, '2024-03-28', FALSE, 'Added metatarsal pad.'),
('Vaginal Yeast Culture', 'Swab collected to identify specific yeast species.', 65.00, 0, '2023-11-02', FALSE, 'Useful for recurrent or resistant infections.'),
('Nasal Polyp Removal (Polypectomy)', 'Endoscopic removal of nasal polyps.', 3800.00, 1, '2024-02-13', TRUE, 'Improves nasal breathing and sense of smell.'),
('Corneal Cross-Linking (CXL)', 'Treatment to strengthen cornea for conditions like keratoconus.', 4000.00, 1, '2024-01-26', TRUE, 'Involves riboflavin drops and UV light.'),
('Spinal Cord Stimulator - Permanent Implantation', 'Surgical placement of permanent SCS device after successful trial.', 35000.00, 3, '2024-03-08', TRUE, 'Generator placed subcutaneously.'),
('Biofeedback for Incontinence', 'Training to improve pelvic floor muscle control.', 160.00, 1, '2024-03-20', TRUE, 'Patient learning to isolate correct muscles.'),
('Vaccination - Rabies Pre-Exposure Prophylaxis (Dose 2)', 'Second dose in pre-exposure rabies series.', 400.00, 0, '2023-10-19', TRUE, 'Continuing immunization schedule.'),
('Adhesiolysis - Laparoscopic', 'Surgical procedure to cut abdominal scar tissue.', 16000.00, 3, '2024-01-11', TRUE, 'Performed for bowel obstruction caused by adhesions.'),
('Developmental Screening Test (e.g., Ages & Stages)', 'Questionnaire or assessment screening child development.', 75.00, 0, '2024-03-19', FALSE, 'Completed by parent or during visit.'),
('Lower Extremity Venous Doppler Ultrasound', 'Imaging veins in legs to check for blood clots (DVT).', 550.00, 1, '2024-03-25', FALSE, 'No evidence of deep vein thrombosis found.'),
('Urine Microalbumin Test', 'Urine test screening for early kidney damage (often in diabetes).', 50.00, 0, '2024-04-03', FALSE, 'Result reported as albumin-to-creatinine ratio.'),
('Sentinel Lymph Node Mapping and Injection', 'Injecting tracer material before surgery to identify sentinel node.', 600.00, 1, '2023-11-13', FALSE, 'Performed in nuclear medicine department.'),
('Gastric Emptying Study', 'Nuclear medicine test measuring how quickly stomach empties.', 700.00, 4, '2024-02-16', FALSE, 'Patient eats meal containing radioactive tracer.'),
('Epiduroscopy', 'Endoscopic examination of the epidural space.', 3500.00, 1, '2024-01-29', TRUE, 'Can be used to diagnose/treat spinal pain.'),
('Osteopathic Manipulative Treatment (OMT)', 'Hands-on treatment by osteopathic physician.', 130.00, 0, '2024-03-09', TRUE, 'Techniques include muscle energy, counterstrain.'),
('Hysteroscopy - Diagnostic', 'Endoscopic examination of the uterine cavity.', 950.00, 1, '2023-12-01', FALSE, 'Performed in office or OR setting.'),
('Liver Elastography (FibroScan)', 'Non-invasive ultrasound test measuring liver stiffness.', 450.00, 0, '2024-02-29', FALSE, 'Helps assess liver fibrosis.'),
('Hand Therapy - Scar Massage', 'Techniques to improve scar mobility and appearance.', 70.00, 0, '2024-02-01', TRUE, 'Demonstrated techniques for home practice.'),
('Cervical Ripening - Misoprostol Administration', 'Medication used to soften/prepare cervix for labor induction.', 200.00, 4, '2023-11-24', TRUE, 'Patient monitored closely after administration.'),
('Viscosupplementation Injection - Knee (Hyaluronic Acid)', 'Injection to supplement joint fluid in osteoarthritis.', 700.00, 0, '2024-03-18', TRUE, 'Often given as a series of injections.'),
('TB Skin Test (PPD) Reading', 'Assessment of skin reaction 48-72 hours after PPD placement.', 20.00, 0, '2024-02-17', FALSE, 'Induration measured and recorded.'),
('Implantable Loop Recorder (ILR) Removal', 'Surgical removal of heart monitoring device.', 900.00, 1, '2024-02-06', FALSE, 'Small incision closed with sutures or adhesive.'),
('Dental Night Guard Delivery and Adjustment', 'Providing patient with custom night guard.', 120.00, 0, '2023-10-20', FALSE, 'Fit and occlusion checked.'),
('Vaccination - Meningococcal B', 'Vaccine protecting against different strains than MenACWY.', 175.00, 0, '2023-11-17', TRUE, 'Recommended for adolescents/young adults based on risk.'),
('Segmental Mastectomy (Lumpectomy) with Axillary Dissection', 'Breast lump removal plus removal of underarm lymph nodes.', 14500.00, 3, '2024-01-19', TRUE, 'Requires post-op drain and monitoring for lymphedema.'),
('Psychological Testing - Personality Assessment (e.g., MMPI)', 'Standardized test assessing personality traits/psychopathology.', 600.00, 3, '2024-03-15', TRUE, 'Interpretation requires qualified psychologist.'),
('Prosthetic Limb Adjustment', 'Modifying fit of artificial limb.', 180.00, 1, '2024-04-05', TRUE, 'Adjustments made for comfort and function.'),
('Anoscopy', 'Examination of the anus and lower rectum with a scope.', 250.00, 0, '2023-12-06', FALSE, 'Often performed for hemorrhoid evaluation.'),
('Laryngoscopy - Flexible Fiberoptic', 'Examination of throat and voice box using flexible scope.', 500.00, 0, '2024-03-02', FALSE, 'Performed in office, topical anesthesia used.'),
('Radioactive Iodine (I-131) Therapy - Hyperthyroidism', 'Oral dose of radioactive iodine to treat overactive thyroid.', 1200.00, 1, '2024-01-23', TRUE, 'Requires radiation safety precautions.'),
('Thoracoscopy with Pleurodesis', 'Minimally invasive chest surgery to prevent recurrent pleural effusion.', 15000.00, 2, '2024-02-20', TRUE, 'Chemical or mechanical irritation creates adhesions.'),
('Lipoma Excision', 'Surgical removal of benign fatty tumor.', 750.00, 1, '2024-03-24', TRUE, 'Simple excision usually curative.'),
('Vestibular Evoked Myogenic Potential (VEMP) Test', 'Test assessing function of part of the inner ear balance system.', 450.00, 1, '2024-01-09', FALSE, 'Involves sound stimulation and muscle response recording.');

select * from treatments
